"""Reusable service integrations for the agent overseas report project."""

from .web_research_service import (
    DEFAULT_WEB_RESEARCH_TOPICS,
    DefaultWebResearchService,
    InMemoryWebResearchSourceRepository,
    WebResearchRequest,
    WebResearchResult,
    WebResearchService,
    WebResearchSource,
    WebResearchSourceRepository,
    WebResearchTask,
    WebResearchTopic,
    WebSearchClient,
    WebSearchResult,
)
from .report_context_builder import (
    CitationContext,
    ContextBundle,
    LocalKnowledgeContext,
    MissingFieldContext,
    ReportContextBuilder,
    RuleEngineContext,
    WebResearchContext,
)
from .rule_engine import OverseasRuleEngine
from .generation_readiness import GenerationReadinessStatus, assess_generation_readiness
from .report_quality_scoring_service import (
    ReportQualityDimensionScore,
    ReportQualityScore,
    ReportQualityScoringService,
    ReportQualityStatus,
)
from .generation_service import (
    AuditLogQuery,
    AuditResultStatus,
    DataNotFoundError,
    EnterpriseDataRepository,
    ExportAuditLog,
    GenerationAuditLog,
    GenerationPreviewResponse,
    GenerationRequest,
    PlanVersionListResponse,
    GenerationServiceError,
    GenerationValidationError,
    InMemoryEnterpriseDataRepository,
    KnowledgeRetriever,
    InMemoryGenerationStore,
    OverseasPlanAuditAction,
    OverseasPlanAuditLog,
    OverseasPlanGenerationService,
    PlanLLMClient,
)
from .excel_export_service import ExcelExportKind, ExcelExportRequest, ExcelExportResult
from .ppt_export_service import PPTExportRequest, PPTExportResult
from .word_export_service import WordExportRequest, WordExportResult, WordReportVersion

from .llm_service import (
    DeepSeekLLMService,
    LLMServiceError,
    LLMConfigurationError,
    LLMEmptyResponseError,
    LLMJsonParseError,
    LLMTimeoutError,
    LLMProviderError,
)

__all__ = [
    "DEFAULT_WEB_RESEARCH_TOPICS",
    "DefaultWebResearchService",
    "InMemoryWebResearchSourceRepository",
    "WebResearchRequest",
    "WebResearchResult",
    "WebResearchService",
    "WebResearchSource",
    "WebResearchSourceRepository",
    "WebResearchTask",
    "WebResearchTopic",
    "WebSearchClient",
    "WebSearchResult",
    "CitationContext",
    "ContextBundle",
    "LocalKnowledgeContext",
    "MissingFieldContext",
    "ReportContextBuilder",
    "RuleEngineContext",
    "WebResearchContext",
    "OverseasRuleEngine",
    "GenerationReadinessStatus",
    "assess_generation_readiness",
    "ReportQualityDimensionScore",
    "ReportQualityScore",
    "ReportQualityScoringService",
    "ReportQualityStatus",
    "AuditLogQuery",
    "AuditResultStatus",
    "DataNotFoundError",
    "EnterpriseDataRepository",
    "ExportAuditLog",
    "GenerationAuditLog",
    "GenerationPreviewResponse",
    "GenerationRequest",
    "PlanVersionListResponse",
    "GenerationServiceError",
    "GenerationValidationError",
    "InMemoryEnterpriseDataRepository",
    "KnowledgeRetriever",
    "InMemoryGenerationStore",
    "OverseasPlanAuditAction",
    "OverseasPlanAuditLog",
    "OverseasPlanGenerationService",
    "PlanLLMClient",
    "ExcelExportKind",
    "ExcelExportRequest",
    "ExcelExportResult",
    "PPTExportRequest",
    "PPTExportResult",
    "WordExportRequest",
    "WordExportResult",
    "WordReportVersion",
    "DeepSeekLLMService",
    "LLMServiceError",
    "LLMConfigurationError",
    "LLMEmptyResponseError",
    "LLMJsonParseError",
    "LLMTimeoutError",
    "LLMProviderError",
]
